### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by ivstepanov** [pypye/rooftop_detection#1]
Hello, I'm trying to study your project on my dataset. When converting the mask to black and white format, I get a two-dimensional array [512, 512], and in your laptop the size of the array is [1, 512, 512].  Could you give an example of the correct data or how do I modify your code to move on.
![1](https://user-images.githubusercontent.com/25278407/202871614-a14bc208-f605-434f-a654-ece6a1b66620.jpg)

**Comment by 0xpye** [comment]
Thanks for feedback. I ran this project on very old Pytorch version. Perhaps they are now removing the array's first axis (like from [1, 512, 512] to [512, 512]). The simplest way to solve this I think is expand the dimension of the label. You can use ```np.expand_dims``` function.
You can modify it like this:
```py

def __getitem__(self, index):
        image = np.array(Image.open(self.image_file[index]).convert("RGB"))
        mask = np.array(Image.open(self.mask_file[index]).
        convert("L"), dtype=np.float32)
        mask[mask > 0.0] = 1.0
        mask = np.expand_dims(mask, axis=0)
```

**Comment by ivstepanov** [comment]
Thank you very much, your solution has eliminated the error. But the problem remained. The mask was not loaded. I understand that it is related to the use of ToTensorV2. I hope that your experience can suggest the right solution. 
![image](https://user-images.githubusercontent.com/25278407/203002108-107b1f64-bc33-422b-8afb-937735c3a793.png)
